url: http://www.greenstop.us
baseurl: ""
include: ["_pages"]

# Site settings
title: GreenSTOP
email: hassan@greenstop.us
description: "GreenSTOP LLC is a “hands off” (ancillary) technology company creating software and hardware applications for the legal cannabis market. Our technology will help expedite, brand, and professionalize the cannabis buying experience in current legal dispensaries."
permalink: /:title/
logo: /img/logos/gslogo_full.png
repository: hassansalman/greenstop-web


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: "UA-86935290-1"
google_ad-client: ""
google_ad-slot: ""  

# Team names, titles and social links
people:
- name: Timothy Island
  bio: 
  pic: tim
  position: Co-Founder/CEO
  social:
    - title: instagram
      url: http://www.instagram.com/futurist_timothy
    - title: facebook
      url: https://www.facebook.com/tim.d.island
    - title: linkedin
      url: https://www.linkedin.com/in/timothy-island-9364b6117


- name: James Edwards
  bio: 
  pic: james
  position: Co-Founder/CEO
  social:
    - title: instagram
      url: https://www.instagram.com/jayrocket_
    - title: facebook
      url: https://www.facebook.com/jayr0cket
    - title: linkedin
      url: https://www.linkedin.com/in/jayrocket


- name: Hassan Salman
  bio: 
  pic: me
  position: Lead Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/hassansalman8
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Michael Strauss
  bio:
  pic: mikeyVC
  position: Finance/Business
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Simeon Russell
  bio:
  pic: simeon
  position: Marketing Advisor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Chris Ramirez
  bio:
  pic: chris
  position: Talent 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #


- name: Paul Randall
  bio:
  pic: paul
  position: Research and Development
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Darien F Rodriguez
  bio: 
  pic: darien
  position: Director/Co-Producer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Pacific Coast Highway
  - line: Redondo Beach, CA 90278

# Build settings
markdown: kramdown
permalink: pretty

gems: [jekyll-seo-tag, jekyll-sitemap, jekyll-github-metadata]
